# Generated by Django 5.0.4 on 2026-05-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_riderequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
