# Generated by Django 5.0.4 on 2026-05-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_remove_emergencyalert_lat_remove_emergencyalert_lng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyalert',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
